config/routes.rb
Rails.application.routes.draw do
  root 'posts#index'
  get '/posts/show_matching_keyword' , to: 'posts#show_matching_keyword'
  get 'posts/search_post', to: 'posts#search_post'
  devise_for :users
  resources :users, only: :show
  resources :posts, only: [:index, :new, :show, :create] do
    resources :likes, only: [:create, :destroy]
    resources :comments, only: :create
  end
  resources :keywords, only: [:index, :create, :edit, :update, :destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :post
end

app/models/keyword.rb
class Keyword < ApplicationRecord
  validates :word, presence: true
  belongs_to :user
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :post, counter_cache: :likes_count
  belongs_to :user
end

app/models/post.rb
class Post < ApplicationRecord
  validates :title, presence: true
  validates :body, presence: true
  belongs_to :user
  has_many :likes, dependent: :destroy
  has_many :comments
  mount_uploader :image, ImageUploader

  def like_user(user_id)
    likes.find_by(user_id: user_id)
  end

  scope :matching_keyword, -> (searchword){ where("title LIKE?", "%#{searchword}%") }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :posts
  has_many :keywords
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
  before_action :devise_strong_parameter, if: :devise_controller?

  private

  def devise_strong_parameter
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :comment_params

  def create
    Comment.create(comment_params)
    redirect_to controller: :posts, action: :show, id: params[:post_id]
  end

  private

  def comment_params
    params.require(:comment).permit(:text).merge(user_id: current_user.id, post_id: params[:post_id])
  end

end

app/controllers/keywords_controller.rb
class KeywordsController < ApplicationController

  def index
    @keyword = Keyword.new
  end

  def create
    @keyword = Keyword.new(keyword_params)
    if @keyword.save
      redirect_to keywords_path, notice: 'キーワードを追加しました'
    else
      flash[:alert] = 'キーワードを追加できませんでした'
      render :index
    end
  end

  def edit
    @keyword = Keyword.find(keyword_params)
    if @keyword.save
      redirect_to :new, notice: 'キーワードを編集しました'
    else
      flash[:alert] = 'キーワードを編集できませんでした'
      render :new
    end
  end

  def destroy
    keyword = Keyword.find(params[:id])
    keyword.destroy
    redirect_to keywords_path, alert: 'キーワードを削除しました'
  end

  private

  def keyword_params
    params.require(:keyword).permit(:word).merge(user_id: current_user.id)
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController

  def create
    create_like
    find_post
    if @post.likes_count
      @likes_count = @post.likes_count
    else
      @likes_count = 0
    end
    respond_to do |format|
      format.html
      format.json
    end
  end

  def destroy
    find_like
    @like.destroy
    find_post
    if @post.likes_count
      @likes_count = @post.likes_count
    else
      @likes_count = 0
    end
  end

  private

  def create_like
    @like = Like.create(post_id: params[:post_id], user_id: current_user.id)
  end

  def find_post
    @post = Post.find(params[:post_id])
  end

  def find_like
    @like = Like.find(params[:id])
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
skip_before_action :verify_authenticity_token

  def index
    respond_to do |format|
      format.html
        @posts = Post.order("created_at DESC").page(params[:page]).per(10)
      format.json
    end
  end

  def show
    @comment = Comment.new
    @post = Post.find(params[:id])
    @comments = @post.comments.includes(:user)
    @user_ids = @post.likes.map{ |like| like.user_id }
    @like = @post.likes.find_by(user_id: current_user.id)
  end

  def new
    @html = view_context.markdown(params[:input]).html_safe if params[:input]
    respond_to do |format|
      format.html
        @post = Post.new
      format.json
    end
  end

  def create
    @post = Post.new(post_strong_params)
    if @post.save
      flash[:notice] = "投稿しました"
      redirect_to action: :index
    else
      flash[:alert] = "投稿できませんでした"
      redirect_to action: :new
    end
  end

  def show_matching_keyword
    keywords_ary = current_user.keywords.map{ |keyword| keyword.word }
    titles = Post.arel_table[:title]
    title_sel = titles.matches("\%#{keywords_ary[0]}\%")
    title_sel = titles.matches("%#{keywords_ary[0]}%")
    for i in 1...keywords_ary.length
      title_sel = title_sel.or(titles.matches("\%#{keywords_ary[i]}\%"))
    end
    # logger.debug("SQL: #{Post.where(title_sel).to_sql}")
    @posts = Post.order("created_at DESC").where(title_sel).page(params[:page]).per(10)
    render 'show_matching_keyword'
  end

  def search_post
    @posts = Post.matching_keyword(params[:keyword]).order("created_at DESC").page(params[:page]).per(10)
    render 'show_matching_keyword'
  end

  private

  def post_strong_params
    params.require(:post).permit(:title, :body, :image).merge(user_id: current_user.id)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
    require "redcarpet"
    require "coderay"

    class HTMLwithCoderay < Redcarpet::Render::HTML
        def block_code(code, language)
            # language = language.split(':')[0]

            case language.to_s
            when 'rb'
                lang = 'ruby'
            when 'yml'
                lang = 'yaml'
            when 'css'
                lang = 'css'
            when 'html'
                lang = 'html'
            when ''
                lang = 'md'
            else
                lang = language
            end

            CodeRay.scan(code, lang).div
        end
    end

    def markdown(text)
        html_render = HTMLwithCoderay.new(filter_html: true, hard_wrap: true)
        options = {
            autolink: true,
            space_after_headers: true,
            no_intra_emphasis: true,
            fenced_code_blocks: true,
            tables: true,
            hard_wrap: true,
            xhtml: true,
            lax_html_blocks: true,
            strikethrough: true
        }
        markdown = Redcarpet::Markdown.new(html_render, options)
        markdown.render(text)
    end
end

app/views/keywords/index.html.haml
!!!5
%html
  %head
    %meta{charset: 'utf-8'}
  %body
    = render 'posts/header'
    .keywords-index-main
      - if current_user.keywords.present?
        %ul{ class: 'keywords-index-main__lists' }
          - current_user.keywords.each do |keyword|
            %li{ class: 'keywords-index-main__lists__list' }
              .keywords-index-main__lists__list__word
                = keyword.word
              = link_to '削除', "/keywords/#{ keyword.id }", method: :delete, class: 'keywords-index-main__lists__list__delete-btn'
            %hr
      - else
        .keywords-index-main__lists
          %span まだキーワードは登録されていません。

      = form_for [@keyword], class: 'keywords-index-main__form' do |f|
        = f.text_field :word, class: 'keywords-index-main__form__input', placeholder: 'キーワードを入力してください'
        = f.submit '追加する', class: 'keywords-index-main__form__input-btn'
    = render 'posts/footer'

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title QiitaCopy
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    - flash.each do |type, msg|
      = content_tag(:div, msg, class: "flash flash__#{type}")
    = yield

app/views/posts/_footer.html.haml
%hr
%footer
  .left-content
    .left-content--black
      = link_to '© 2011-2017 IncrementsInc.', root_path
    .left-content--blue
      = link_to '利用規約', root_path
      = link_to 'プライバシー', root_path
      = link_to 'ヘルプ', root_path
      = link_to 'お問い合わせ', root_path
  .right-content
    = link_to 'Qiitaとは', root_path
    = link_to 'ユーザー', root_path
    = link_to 'タグ', root_path
    = link_to 'ブログ', root_path
    = link_to 'API', root_path
    = link_to 'Team', root_path
    = link_to 'Kobito', root_path
    %a{ href: '/' }
      %i.fa.fa-heart
      ご意見
      %i.fa.fa-caret-down

app/views/posts/_header.html.haml
%header
  .left-content
    = link_to image_tag('qiita_logo.png'), root_path, class: 'left-content__qiita-logo'
    = form_tag posts_search_post_path, method: :get do
      %input{ class: 'left-content__input', name: 'keyword', placeholder: 'キーワードを入力' }
    .left-content__news
      .left-content__news__title
        %p news
      .left-content__news__text
        ストックの他にいいねが追加されました。
  .right-content
    = link_to image_tag('qiita_profile_icon.png', size: '35x35'), root_path, class: 'right-content__profile'
    %ul{ class: 'user_dropdown' }
      %li
        %a{ href: "/users/#{ current_user.id }", class: 'user_dropdown__my-page' }
          %i{ class: 'fa fa-fw fa-user' }
          マイページ
      %li
        %a{ href: "/", class: 'user_dropdown__setting' }
          %i{ class: 'fa fa-fw fa-cog' }
          設定
      %li
        %a{ href: "/", class: 'user_dropdown__help' }
          %i{ class: 'fa fa-fw fa-question' }
          ヘルプ
      %li
        %a(href="/users/sign_out" class='user_dropdown__logout' data-method='delete' )
          %i{ class: 'fa fa-fw fa-sign-out' }
          ログアウト
    = link_to '0', root_path, class: 'right-content__notice'
    = link_to 'ストック一覧', root_path, class: 'right-content__stock'
    .right-content__post
      %a{ href: '/posts/new' }
        %i.right-content__post__input__icon.fa.fa-pencil-square-o
        投稿する
        %i.right-content__post__input__icon.fa.fa-caret-down

app/views/posts/_posts.haml
.main__body__posts
  - posts.each do |post|
    .main__body__posts__post
      = image_tag 'https://s3-ap-northeast-1.amazonaws.com/qiita-tag-image/a366fc34caa85747b6b377c761c983a9a99b4ddb/large.jpg?1489110713', class: 'main__body__posts__post__pg-lung-img', size: '30x30'
      %i.fa.fa-tag
      .main__body__posts__post__info
        .main__body__posts__post__info__text
          Railsに新しい投稿がありました
        .main__body__posts__post__info__good
          %i.fa.fa-thumbs-o-up
            - if post.likes_count
              = post.likes_count
            - else
              0
      = link_to post.title, post_path(post), class: 'main__body__posts__post__title'
  = paginate @posts

app/views/posts/_sidebar.haml
.main__side
  .main__side__advertisement
    = image_tag 'advertisement.png', size: '250x250'
  .main__side__account
    .main__side__account__left
    = link_to image_tag('qiita_profile_icon.png', size: '65x65'), "/users/#{ current_user.id }", class: 'main__side__account__left'
    .main__side__account__right
      = link_to current_user.name, "/users/#{ current_user.id }", class: 'main__side__account__right__name'
      .main__side__account__right__action
        %span
          = current_user.posts.length
          投稿
        %span 0 contribution
  .main__side__feed

app/views/posts/index.haml
!!!5
%html
  %head
    %meta{charset: 'utf-8'}
  %body{ class: 'index' }
    = render 'header'
    .main
      .main__header
        %h2.main__header__title
          プログラミングの知識を共有しよう。
        = link_to 'ノウハウ・Tipsを投稿する', root_path, class: 'main__header__btn'
      .main__body
        .main__body__tag
          = link_to '全て', root_path, class: 'main__body__tag--feed'
          = link_to 'キーワード', '/posts/show_matching_keyword', class: 'main__body__tag--all-posts'
          = link_to '自分の投稿', root_path, class: 'main__body__tag--my-posts'
        = render partial: 'posts', locals: { posts: @posts }
      = render 'sidebar'
    = render 'footer'

app/views/posts/index.html.haml
Hello, Qiita!

app/views/posts/new.haml
!!!5
%html
  %head
    %meta{ charset: 'utf-8' }
  %body
    = form_for @post do|f|
      .dody
        = render 'header'
        .main-new
          .main-new__title
            = f.text_field :title, placeholder: 'タイトル', class: 'main-new__title__input'
          .main-new__tag
            %input{ placeholder: 'プログラミング技術に関連するタグをスペース区切りで５つまで入力（例:Ruby Rails:4.2.0）', class: 'main-new__tag__input' }
          .main-new__body
            .main-new__body__left
              .main-new__body__left__tag
                .main-new__body__left__tag__left
                  .main-new__body__left__tag__left__body
                    本文
                  .main-new__body__left__tag__left__good-post
                    %i.fa.fa-book
                    %a{ href: '/' }
                      良い記事を書くには
                .main-new__body__left__tag__right
                  %i.fa.fa-question-circle.fa-2x
                  %i.fa.fa-smile-o.fa-2x
                  = f.label :image, { class: "fa fa-photo fa-2x", for: "file_field" } do
                    = f.file_field :image, style: "display: none;", id: "file_field"
              .main-new__body__left__text
                = f.text_area :body, placeholder: 'プログラミングの知識をmarkdown記法で書いて共有しよう', class: 'main-new__body__left__text__input'
          .main-new__body__right
            .main-new__body__right__tag
              %a{ href: '/' }
                %i.fa.fa-angle-left
              %a{ href: '/' }
                %i.fa.fa-angle-right
            .main-new__body__right__cheetsheet
              .main-new__body__right__cheetsheet__markdown
              .main-new__body__right__cheetsheet__image
              .main-new__body__right__cheetsheet__title
                %i.fa.fa-question-circle
                Markdown記法のヒント
              .main-new__body__right__cheetsheet__example
                .main-new__body__right__cheetsheet__example__left
                  .main-new__body__right__cheetsheet__example__left__title
                    見出し
                  .main-new__body__right__cheetsheet__example__left__content
                    %p # 見出し 1
                    %p ## 見出し 2
                    %p ### 見出し 3

                  .main-new__body__right__cheetsheet__example__left__title
                    %p ライン
                  .main-new__body__right__cheetsheet__example__left__content
                    %p - - -

                  .main-new__body__right__cheetsheet__example__left__title
                    %p コード
                  .main-new__body__right__cheetsheet__example__left__content
                    %p ```
                    %p コード
                    %p ```
                .main-new__body__right__cheetsheet__example__right
                  .main-new__body__right__cheetsheet__example__right__title
                    %p リスト
                  .main-new__body__right__cheetsheet__example__right__content
                    %p - リスト 1
                    %p - リスト 2
                    %p - リスト 3
                    %p スペースを入れると色が変わります。
                  .main-new__body__right__cheetsheet__example__right__title
                    %p リスト②
                  .main-new__body__right__cheetsheet__example__right__content
                    %p * リスト 1
                    %p * リスト 2
                    %p * リスト 3
                    %p スペースを入れると色が変わります。

                  .main-new__body__right__cheetsheet__example__right__content
                    %p 1. 番号付きリスト 1
                    %p 2. 番号付きリスト 2
                    %p 3. 番号付きリスト 3
        .footer-new
          .btn
            %i.fa.fa-upload
            = f.submit 'Qiitaに投稿'
            %i.fa.fa-caret-up

app/views/posts/show.haml
!!!5
%html
  %head
    %meta{charset: 'utf-8'}
  %body
    = render 'header'
    .post-main
      .post-main__header
        .post-main__header__title
          = @post.title
        .post-main__header__evaluation
          .post-main__header__evaluation__good
            %i.fa.fa-thumbs-o-up
            %span
              = @post.likes_count
            %p いいね
          .post-main__header__evaluation__comment
            %i.fa.fa-comment-o
            %span 0
            %p コメント
        - if @like.nil?
          %div{ class: 'post-main__header__good-btn', post_id: "#{ @post.id }" }
            .post-main__header__good-btn--push
              %i.fa.fa-thumbs-o-up
              %span いいね
        - else
          %div{ class: 'post-main__header__good-btn', post_id: "#{ @post.id }" }
            %div{ class: 'post-main__header__good-btn--pushed', like_id:  "#{ @like.id }" }
              %i.fa.fa-thumbs-o-up
              %span いいね済みです
      .post-main__creater
        .post-main__creater__left
          = link_to image_tag('qiita_profile_icon.png', size: '30x30'), root_path, class: 'post-main__creater__left__account-image'
          %ul{ class: 'user_dropdown' }
            %li
              %a{ href: "/users/#{ current_user.id }", class: 'user_dropdown__my-page' }
                %i{ class: 'fa fa-fw fa-user' }
                マイページ
            %li
              %a{ href: "/", class: 'user_dropdown__setting' }
                %i{ class: 'fa fa-fw fa-cog' }
                設定
            %li
              %a{ href: "/", class: 'user_dropdown__help' }
                %i{ class: 'fa fa-fw fa-question' }
                ヘルプ
            %li
              %a(href="/users/sign_out" class='user_dropdown__logout' data-method='delete' )
                %i{ class: 'fa fa-fw fa-sign-out' }
                ログアウト
          .post-main__creater__left__account-name
            = link_to @post.user.name, user_path(@post.user)
          .post-main__creater__left__date
            = @post.created_at.strftime('%Y年%m月%d日')
            に投稿
        .post-main__creater__right
          %a{ href: '/', class: 'post-main__creater__right__stock-btn' }
            %i.fa.fa-folder-open
            %span ストック
          %a{ href: '/', class: 'post-main__creater__right__dropdown' }
            %i.fa.fa-ellipsis-h
      .post-main__body
        .post-main__body__content
          .post-main__body__content__text
            = markdown(@post.body).html_safe
          .post-main__body__content__image
            - if @post.image
              = image_tag(@post.image)
          .post-main__body__content__footer
            .post-main__body__content__footer__left
              / %a{ href: '/', class: 'post-main__body__content__footer__left__good-btn' }
              /   %i.fa.fa-thumbs-o-up
              /   %span いいね
              / .post-main__body__content__footer__left__good-num
              /   %p 0
            .post-main__body__content__footer__right
              %a{ href: '/', class: 'post-main__body__content__footer__right__stock-btn' }
                %i.fa.fa-folder-open
                %span ストック
              %a{ href: '/', class: 'post-main__body__content__footer__right__edit-request' }
                %i.fa.fa-send-o
                %span 編集リクエスト
              %a{ href: '/', class: 'post-main__body__content__footer__right__dropdown' }
                %i.fa.fa-ellipsis-h

          - if @comments.present?
            .post-main__body__content__comments
              - @comments.each do |comment|
                .post-main__body__content__comments__comment
                  .post-main__body__content__comments__comment__header
                    .post-main__body__content__comments__comment__header__left
                      = image_tag('qiita_profile_icon.png', size: '36x36')
                      = link_to comment.user.name, user_path(comment.user)
                    .post-main__body__content__comments__comment__header__right
                      = comment.created_at.strftime("%Y-%m-%d %H:%M")
                  .post-main__body__content__comments__comment__text
                    = simple_format(comment.text)
          %span コメントを投稿する
          .post-main__body__content__comment__main
            .post-main__body__content__comment__main__tags
              .post-main__body__content__comment__main__tags__left
                %span.post-main__body__content__comment__main__tags__left__edit
                  編集
                %span.post-main__body__content__comment__main__tags__left__preview
                  プレビュー
              .post-main__body__content__comment__main__tags__right
                %a{ href: 'http://qiita.com/Qiita/items/c686397e4a0f4f11683d', class: 'post-main__body__content__comment__main__tags__right__markdown' }
                  Qiita Markdown?
                  %i.fa.fa-smile-o.fa-2x
            = form_for [@post, @comment] do |c|
              = c.text_area :text, placeholder: 'コメントを入力してください', class: 'post-main__body__content__comment__main__input'
              = c.submit "投稿", class: 'post-main__body__content__comment__footer__submit'
          .post-main__body__content__comment__footer
            %a{href: '/', class: 'post-main__body__content__comment__footer__input-image' }
              %i.fa.fa-photo
              画像を選択
            %span またはドラッグ＆ドロップ

            / %button{ type: 'submit', value: '投稿', class: 'post-main__body__content__comment__footer__submit' }
            /   投稿
        .post-main__body__sidebar
          .post-main__body__sidebar__account
            = link_to image_tag('qiita_profile_icon.png', size: '45x45'), root_path, class: 'post-main__body__sidebar__account__image'
            = link_to @post.user.name, "/users/#{@post.user.id}", class: 'post-main__body__sidebar__account__name'
            %a{ href: '/'}
              %i.fa.fa-user-plus
              %span フォロー
          .post-main__body__sidebar__popular-posts
            %h6.post-main__body__sidebar__popular-posts__title
              人気の投稿
            %ul
              %li
                = link_to '人気の記事1', '/'
              %li
                = link_to '人気の記事2', '/'
              %li
                = link_to '人気の記事3', '/'
              %li
                = link_to '人気の記事4', '/'
              %li
                = link_to '人気の記事5', '/'
    %footer
      %hr
      .left-content
        .left-content--black
          = link_to '© 2011-2017 IncrementsInc.', root_path
        .left-content--blue
          = link_to '利用規約', root_path
          = link_to 'プライバシー', root_path
          = link_to 'ヘルプ', root_path
          = link_to 'お問い合わせ', root_path
      .right-content
        = link_to 'Qiitaとは', root_path
        = link_to 'ユーザー', root_path
        = link_to 'タグ', root_path
        = link_to 'ブログ', root_path
        = link_to 'API', root_path
        = link_to 'Team', root_path
        = link_to 'Kobito', root_path
        %a{ href: '/' }
          %i.fa.fa-heart
            ご意見
          %i.fa.fa-caret-down

app/views/posts/show_matching_keyword.haml
!!!5
%html
  %head
    %meta{charset: 'utf-8'}
  %body
    = render 'header'
    .main
      .main__header
        %h2.main__header__title
          プログラミングの知識を共有しよう。
        = link_to 'ノウハウ・Tipsを投稿する', root_path, class: 'main__header__btn'
      .main__body
        .main__body__tag
          = link_to '全て', root_path, class: 'main__body__tag--feed--keyword'
          = link_to 'キーワード', '/posts/show_matching_keyword', class: 'main__body__tag--all-posts--keyword'
          = link_to '自分の投稿', root_path, class: 'main__body__tag--my-posts--keyword'
        = render partial: 'posts', locals: { posts: @posts }
        - if current_user.keywords.empty?
          %p キーワードにマッチする記事はありません
      = render 'sidebar'
    = render 'footer'

app/views/users/show.haml
!!!5
%html
  %head
    %meta{charset: 'utf-8'}
  %body
    = render 'posts/header'
    .main
      .main__left-content
        = image_tag 'qiita_profile_icon.png', class: 'main__left-content__account-image'
        .main__left-content__account-detail
          .main__left-content__account-detail__name
            = current_user.name
          %hr
          .main__left-content__account-detail__edit
            %a{ href: '/' }
              %i.fa.fa-cog
              プロフィールを編集する
          %hr
          .main__left-content__account-detail__keyword
            %i.fa.fa-fw.fa-tags
            %span 登録キーワード
            = link_to '(編集する)', keywords_path
            .main__left-content__account-detail__follow__number
              = current_user.keywords.length
          .main__left-content__account-detail__keyword-list
            - if current_user.keywords.present?
              - current_user.keywords.each do |keyword|
                = keyword.word
            - else
              %span 登録しているキーワードはありません
      .main__right-content
        .main__right-content__graph
        .main__right-content__big-tag
          %a{ href: '/', class: 'main__right-content__big-tag__items' }
            .main__right-content__big-tag__items__number 0
            %p items
          %a{ href: '/', class: 'main__right-content__big-tag__contribution' }
            .main__right-content__big-tag__contribution__number 0
            %p contribution
          %a{ href: '/', class: 'main__right-content__big-tag__followers' }
            .main__right-content__big-tag__followers__number 0
            %p followers
        %ul.main__right-content__small-tag-title
          %li.main__right-content__small-tag-title__recent-post
            %a{ href: '/' }
              最近の投稿
              %span 0
          %li.main__right-content__small-tag-title__pressed-like
            %a{ href: '/' }
              いいねした投稿
          %li.main__right-content__small-tag-title__limitted-share
            %a{ href: '/' }
              限定共有投稿
          %li.main__right-content__small-tag-title__comment
            %a{ href: '/' }
              コメント
        %hr
        .main__right-content__small-tag-detail
          .main__right-content__small-tag-detail__text
            = current_user.name
            さんの投稿はありません。

    = render 'posts/footer'